### ISSUE TITLE
ssh keys?

### ISSUE THREAD

**Issue by hobu** [OSGeo/homebrew-osgeo4mac#731]
@fjperini Is there a reason why the ssh keys for this repository are changing so much? Are they changing with an automated system or something? It would seem not to be such a good idea to be giving an automated system the ability to modify the keys to this repository.

**Comment by fjperini** [comment]
@hobu We use Travis CI to build the bottles, there was no change recently in the keys for their use.

Yes for Circle CI. There are several things that change and I am trying to make it work.
It has an inconvenience when decrypting and in the format of the key. This should not happen.

We seek to use CI Cricle for construction times and to solve other issues.

**Comment by fjperini** [comment]
It seems that Circle CI has trouble decrypting the keys, that's why the errors `iv undefined` and `invalid format`.

And this form does not seem to be working (this requires a key without a password):

```
      # Add deployment key fingerprint for CircleCI to use for a push
      - add_ssh_keys:
          fingerprints:
            - "${KEY_FINGERPRINT}"
      - run:
          name: Avoid hosts unknown for github
          command: |
            echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
```
```
There are no configured ssh keys to install
```
